# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be58637f6b542e0e547896c424bd088a6457c5fa3ca99b126589041d639fb1c290716e7bf0b95c6d98b77e17cb9c05328dad369ef2b685b88beb36c0a8def5b2

test:
  secret_key_base: 534572a0f8f88cc09417161445470ecdeaa54c393c00dedd68a69e795f7e00e3da1536ba67ca1bd7e4fcbf912133cedb64d802d3fce3d462a3d2ffde5dc04adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
